### ISSUE TITLE
Fix client - server logic

### ISSUE THREAD

**Issue by ersonp** [skycoin/dmsg#112]
**Describe the bug**
- Even if multiple servers are available the client will only connect to 2 on startup.
- If the client is only connected to one server and the server stops, then it will make a connection with just one new server even if multiple are available.
- At times the client did connect to 3 servers but i could't figure out the reasons why.

**Environment information:**

- OS: e.g. Linux
- Platform: Linux 5.11.0-34-generic x86_64

**Steps to Reproduce**

1. Start integration env in `skywire-services`
2. Run 3 separate `dmsg- servers`
3. In `skywire-services/integration/generic/visorA.json` change `log_level` to `debug`.
4. Restart visorA in integration env.
5. Check if 2 dmsg-servers are registered by the client (visor).
6. Close `dmsg-servers` and see how the client(visor) responds.

**Comment by mrpalide** [comment]
Test again on ‍dmsg#5c5ff2c and skywire#c76b45a, with 4 multiple dmsg-servers, and everything looks OK.
