### ISSUE TITLE
Failing dmsg tests

### ISSUE THREAD

**Issue by ersonp** [skycoin/dmsg#118]
**Describe the bug**
DMSG tests sometimes fail on AppVeyor. 

**Environment information:**

- OS: e.g. Linux, Mac OS X (AppVeyor)

**Actual behavior**

[linux.txt](https://github.com/skycoin/dmsg/files/7304792/linux.txt)
[macos.txt](https://github.com/skycoin/dmsg/files/7304793/macos.txt)

**Comment by jdknives** [comment]
Fixed by #126
