### ISSUE TITLE
Stream between two clients via the same server is unstable

### ISSUE THREAD

**Issue by ersonp** [skycoin/dmsg#125]
**Describe the bug**
When trying to connect to a remote client via a static dmsg server the connection fails sometimes. While testing the failure rate has differed between different local clients of different testers. (while the remote client and server being the same)

**Environment information:**

- OS: e.g. Linux
- Platform: Linux 5.11.0-38-generic x86_64

**Steps to Reproduce**
Needs access to https://github.com/ersonp/dmsg-http

1. Run `make build`
2. Run `./bin/dmsgdirect dmsg://<http-server-pk>:80/hello.txt` multiple times (server instructions are provided in the repo)

**Actual behavior**
[fail.txt](https://github.com/skycoin/dmsg/files/7459833/fail.txt)
[success.txt](https://github.com/skycoin/dmsg/files/7459834/success.txt)

**Comment by jdknives** [comment]
Deemed to be connection issue.
