### ISSUE TITLE
Visors on `dmsghttp` stop working with visors on `http`

### ISSUE THREAD

**Issue by ersonp** [skycoin/dmsg#154]
The issue with services over `dmsghttp` is that randomly (as far as I know) the service will stop showing logs from the `dmsghttp` connection but the visor will run without any errors and everything will work as normal if both visors are on `dmsghttp` or if both of them are on `http` but won't work if both are on different ones. 
For eg if `address-resolver` is having this issue then if

| | dmsghttp | http | works |
| --- | --- | --- | --- |
| Visor A | ✔ | ✔ | no |
| Visor B | ✔ | ✔ | no |
| Works | yes | yes | |

And no logs are shown in `address-resolver` even when it's working

**Comment by mrpalide** [comment]
Test by using Skychat, and no problems see on logs. [skywire#c76b45a0]
[directhttp-log.txt](https://github.com/skycoin/dmsg/files/8753418/directhttp-log.txt)
[dmsghttp-log.txt](https://github.com/skycoin/dmsg/files/8753419/dmsghttp-log.txt)
