### ISSUE TITLE
Connect to different dmsg-server if the connection to the first one fails

### ISSUE THREAD

**Issue by ersonp** [skycoin/dmsg#159]
**Describe the bug**
Currently, if the dmsg is unable to connect to the first dmsg-server it tries to connect to it again after 20 seconds but is stuck on that server for a long time instead of choosing another server to connect to.

**Environment information:**

- OS: e.g. Linux
- Platform: Linux 5.13.0-28-generic x86_64

**Steps to Reproduce**

1. Make prod config `./skywire-cli config gen -ir`
2. Start the visor `./skywire-visor -c skywire-config.json` (Might have to do it multiple times)
3. If the visors tries to connect to a `dmsg-server` with low `AvailableSessions` then they could be filled up by the time the visor make the connection and the visor won't be able to connect to the `dmsg-server`

**Comment by mrpalide** [comment]
Actually even with mock data like `https://run.mocky.io/v3/f8347d7b-6235-4c99-a390-840f5ebb87ff` error cannot reproduce again.
