### ISSUE TITLE
support running multiple dmsg / dmsghttp servers

### ISSUE THREAD

**Issue by 0pcom** [skycoin/dmsg#197]
Currently it is only possible to run a single dmsghttp server. This may also be a limitation for dmsg.

It should be possible to run multiple dmsg or dmsghttp servers by specifying a different dmsg port or using a different public key.

**Comment by mrpalide** [comment]
Currently possible to run multiple dmsg-server with multiple PK and multiple Port. Should we change it or is sufficient?

Test by these two configs:
[configs.zip](https://github.com/skycoin/dmsg/files/9898839/configs.zip)
