### ISSUE TITLE
Expire dmsg clients from dmsg-discovery entries ; hourly re-registration of dmsg clients

### ISSUE THREAD

**Issue by 0pcom** [skycoin/dmsg#247]
Counting the number of entries in dmsg-discovery:
https://dmsgd.skywire.skycoin.com/dmsg-discovery/entries

```
$ curl -L https://dmsgd.skywire.skycoin.com/dmsg-discovery/entries | awk -F "," '{print NF-1}'
10700
```

There are 10700 dmsg client entries in dmsg-discovery.

Counting the number of visors online:

```
$ skywire-cli ut -os
3300 visors online
```

While it's not impossible that we have twice the number of dmsg clients as visors online, *it's highly unlikely that this is the case*

On checking that dmsg client entries are removed after dmsgcurl, it seems that they are removed appropriately on clean exit.

## Solution

* Expire dmsg client entries from dmsg-discovery after 1 hour.

* Long-lived dmsg clients should re-register or refresh their entry in dmsg-discovery hourly by some mechanism.

## Related issues:

https://github.com/skycoin/skywire-services/issues/38
https://github.com/skycoin/skywire-service-discovery/issues/1
https://github.com/skycoin/skywire/issues/1715

**Comment by mrpalide** [comment]
As re-register (heartbeat) logic is expensive, we run dmsg-monitor.
Also we will have new/improve logic on register dmsg clients to discovery that will fix deregister non-visor entries issue.
