### ISSUE TITLE
Basic Fallover 

### ISSUE THREAD

**Issue by jdknives** [skycoin/dmsg#49]
**Feature description**

Dsmg Clients should connect to at least 3 dmsg.Servers upon startup and be able to try to redial to a remote client immediately if the connection via a dmsg.Server is broken. 

**Is your feature request related to a problem? Please describe.**

Currently the clients just report the broken connection but do not try to re-establish a stream via a different dmsg.Server which would improve resiliency of the connection. 

**Describe the solution you'd like**

Make sure the dmsg.Client has multiple sessions with dmsg.Servers established and falls over to another dmsg.Server in case of a server error. 

**Additional context**
We need to make sure that the dmsg.Discovery supports registering multiple servers with a client already and we probs need to scale up the number of dmsg.Servers a bit.

**Comment by mrpalide** [comment]
https://user-images.githubusercontent.com/79150699/170242771-b4fe526e-a8b4-4e2a-a73a-c8bf7d9589f0.mp4
